### PR TITLE
Hugo migration

### PR DESCRIPTION
**Pull request by michael-erasmus**
Hey @DreamingInBinary! As we discussed, here is a PR to migrate the site to Hugo! This will change the dev flow slightly since the static site content is actually in a separate repo from the Hugo code. 

This PR works with the new repo at: https://github.com/bufferapp/buffer-opensource
This new repo will include this current repo as a submodule. I included instructions on how set it up and make changes in it's [README file](https://github.com/bufferapp/buffer-opensource/blob/master/README.md).

I created a custom theme for the Hugo site (https://github.com/bufferapp/buffer-opensource/tree/master/themes/buffer-foss) which has the migrated `index.html` page from the existing site, but wraps the logic for adding new projects so that they can be declaratively defined in a configuration file in the `data/projects` directory, without adding new markup.

Hope that makes sense! Let me know if you had any questions!

One funny thing I noticed when I migrated the index page over, it seems like the [current page](https://github.com/bufferapp/bufferapp.github.io/blob/master/index.html) isn't quite well formed (it has no closing `</body>` or `</hml>` tags). Not a big problem, but I thought I might mention it 😄

### CODE REVIEW

**Comment by DreamingInBinary** [comment]
Sweet stuff @michael-erasmus - thanks for taking the time to put this together 💯!

I installed Hugo and had everything up and running super quick 🎉! A few things I had questions on, as I am not too familiar with Hugo:

- Right now, I'm not quite sure of how the Git process works. I see that it's super easy to add new projects in the `.toml` files (really, really slick!). If I were to add one now (say a new repo under the iOS project) - what do I do next? I _think_ merge the `.toml` file change to the `buffer-opensource` repo? Or the existing `bufferapp.github.io` repo? I wasn't quite sure when reading the readme 🙈. I see in step 6 it says to commit to the existing repo we have now but I guess that confused me since there is no `.toml` file there? Sorry for misunderstanding!

- Does Hugo still allow some good flexibility to change stuff around? For the future - I was planning on making another tab for side projects, and possibly one for snackchats too. I'm not sure how to do this with Hugo right now? It appears to have markdownish kinda thing going on with its `.toml` files which seem to more or less act like templates.

All in all I'm excited by this and it feels great to think about ways to make things easier on us to get our open source stuff out there! I think some input from @djfarrelly might be awesome here too, in terms of how Hugo feels/if it helps us move faster/adapt to future changes/etc.

Thanks!

**Comment by michael-erasmus** [comment]
Hey @DreamingInBinary!

Thanks for the awesome questions! I can totally understand how it might be a bit confusing, and a lot of Hugo is still pretty new to me too! I started writing one big response and it became a bit long, so I'm breaking it up in a couple of replies below!

**Comment by michael-erasmus** [comment]
@DreamingInBinary 
> If I were to add one now (say a new repo under the iOS project) - what do I do next? I think merge the .toml file change to the `buffer-opensource` repo

This is probably the biggest thing about working with Hugo that threw me too :D Basically the [`buffer-opensource`](https://github.com/bufferapp/buffer-opensource) repo becomes your main entrypoint to make any changes and test them out locally before deploying. 

The `bufferapp.github.io` repo is just a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) (like a pointer to another git repo from within a git repo) that now lives in the `public` folder of the main repo. You don't don't edit the files in `public` directory manually at all, instead you let Hugo generate them and only commit and push changes to the submodule when you want to redeploy them to `bufferapp.github.io`


So this pull request I sent is actually the new site that was generated by Hugo, after I made the changes in the parent `buffer-opensource` repo.


So with Hugo, you would actually not work with the `bufferapp.github.io` repo directly anymore. Instead, you would start by cloning the `buffer-opensource` repo and then pulling in the submodule too:

```
git clone --recursive https://github.com/bufferapp/buffer-opensource

```

**Comment by michael-erasmus** [comment]
@DreamingInBinary 

>Does Hugo still allow some good flexibility to change stuff around? For the future - I was planning on making another tab for side projects, and possibly one for snackchats too. I'm not sure how to do this with Hugo right now?

Ah good one! Hugo has the idea of themes, which is basically just the outline for your site, which you can fill in with generic content, usually defined as markdown. It's very similar to Wordpress themes, although they feel a lot more lightweight. Themes are just plain html, js, css and other static content like images.

 What I did for our site was to create a custom theme that basically is just a copy of the index.html as a template. The only small change I made is that it can load projects dynamically using a 'partial'. 

This is sort of like a way to loop through the projects defined in the toml files and render a list of them as markup. This happens over [here](https://github.com/bufferapp/buffer-opensource/blob/master/themes/buffer-foss/layouts/index.html#L236-L238) and the partial that it renders is over [here](https://github.com/bufferapp/buffer-opensource/blob/master/themes/buffer-foss/layouts/partials/project.html)

Normally if you wanted to add a menu or tabs you can do that by tweaking your theme making the actual tabs configurable and make adding new content easy.

 For instance, on my personal blog I've been using this open source theme: https://github.com/halogenica/beautifulhugo, which is designed to be able to have separate menu items on the site by adding the following configuration in site's the config.toml file:

``` 
[[menu.main]]
  name = "Blog"
  url = "/"
  weight = 1

[[menu.main]]
  name = "About"
  url = "/page/about/"
  weight = 3
```

The theme then has a template to dynamically build up the menu using this configuration. Here is where this happens for this specific theme:

https://github.com/halogenica/beautifulhugo/blob/master/layouts/partials/nav.html#L15-L37

Adding the actual page that the menu item will point to is then done by using the hugo command line:

```
hugo new page/about.md
```

The content of this page is just markdown and you don't need to include any of the common elements of your site (like the header and footer and all the html boilerplate) in this file, it's all in the theme.

So in our case we could also change the [`index.html`](https://github.com/bufferapp/buffer-opensource/blob/master/themes/buffer-foss/layouts/index.html) file of our theme to have tabs (or we could even move it to partial `header.html` file to organize things a bit more)

**Comment by michael-erasmus** [comment]
Also just wanted to mention that I've found [Hugo's](https://gohugo.io/overview/introduction/) documentation to be pretty good!

**Comment by michael-erasmus** [comment]
@DreamingInBinary 

> If I were to add one now (say a new repo under the iOS project) - what do I do next?

So in this situation, the steps would be:

1. Go to the `buffer-opensource` repo and add a new project in the iOS project .toml file

 ```toml
[[projects]]
name =  "CoolProject"
repo = "my-cool-project"
description = "My cool new iOS project"

```

2.  (Optional) Test how the site looks with your new change by running the Hugo test server locally (http://localhost:1313)

```
hugo server
```

3. If everything looks ok, run Hugo to actually generate the new static site

```
hugo
```

4. At this point, the new static site changes would have been made in the `public` directory, which is also the `github.bufferapp.io` submodule. To deploy the changes live you can just commit the changes and push to master

```
cd public
git add --all
git commit -m "Added my new cool iOS project"
git push origin master
```

5. At this point, the changes should be on https://bufferapp.github.io! However, we haven't committed the changes to our parent repo yet, so that's one more step:

```
cd ..
git add --all
git commit -m "Added my new cool iOS project"
git push origin master
```

I hope that makes sense! I tried to explain the steps as well as I could in the [README](https://github.com/bufferapp/buffer-opensource/blob/master/README.md), but I can always try make things clearer!

**Comment by michael-erasmus** [comment]
Also just wanted to mention that I've found Hugo's documentation to be pretty good!

**Comment by DreamingInBinary** [comment]
Thanks for the breakdown here @michael-erasmus - that was great! Hugo indeed looks like it could give us some wins in adding projects and such with a bit more ease.

Thinking it over, it feels great to me for a few reasons:

1) As you mentioned, the main thing is we can add more projects trivially 
2) Should make the whole flow faster
3) Also, I just love learning new things 😄 Hugo would be fun to dive into some more

The only thing I might add is, if I make tweaks in the future - I may need to tap on your shoulder to get some things moving if I get a bit stuck, if that sounds good?

Anyways - feel free to merge and let's Hugo our way to the top of the open source world :)

**Comment by michael-erasmus** [comment]
Hey @DreamingInBinary! Thanks, that awesome to hear! Yeah, Hugo has a little bit of a learning curve, but I can see it making simple things like adding content really easy and everything else like changing the layout of the site much more structured.


> The only thing I might add is, if I make tweaks in the future - I may need to tap on your shoulder to get some things moving if I get a bit stuck, if that sounds good?

Sure, I would be happy to help out! To be honest I haven't done much web dev in a while and really enjoyed diving back in a bit here.

**Comment by DreamingInBinary** [comment]
Hey hey @michael-erasmus - sorry for the delay on my end! This feels great to merge to me! If you'd rather, I'm happy to merge it as well :D. Thanks for all of your hard work here to make open source easier for us 🎉 !

**Pull request merged**
